spring:
  application:
    name: libraryapi

  datasource:
    url: jdbc:postgresql://localhost:5433/financas_db
    username: ${DATA_USER}
    password: ${DATA_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    #
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 9090