spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/financas_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-autor: update (atualiza sozinho)
      ddl-auto: none
    properties:
      hibernate.format_sql: true
server:
  port: 9090